"""TGSeqLoc: text-graph place recognition building blocks."""

from .artifacts import (
    ArtifactError,
    ArtifactManifest,
    ArtifactPolicy,
    ArtifactRecord,
    ArtifactStore,
    IncompatibleArtifactError,
    canonical_json,
    file_sha256,
    fingerprint,
)
from .config import (
    AppConfig,
    CacheConfig,
    ConfigError,
    DatasetConfig,
    ModelConfig,
    OutputConfig,
    PreprocessConfig,
    RetrievalConfig,
    RuntimeConfig,
    SourceConfig,
    SourcesConfig,
    TrainingConfig,
    dump_config,
    load_config,
)
from .components import component_map, register_builtin_components
from .pipeline import PipelineRunner
from .registry import (
    Dataset,
    Encoder,
    Filter,
    Fusion,
    GraphEncoder,
    Metric,
    Miner,
    Registry,
    Reranker,
    Retriever,
    Source,
    register,
    registry,
)

__version__ = "0.1.0"

__all__ = [
    "AppConfig",
    "ArtifactError",
    "ArtifactManifest",
    "ArtifactPolicy",
    "ArtifactRecord",
    "ArtifactStore",
    "CacheConfig",
    "ConfigError",
    "Dataset",
    "DatasetConfig",
    "Encoder",
    "Filter",
    "Fusion",
    "GraphEncoder",
    "IncompatibleArtifactError",
    "Metric",
    "Miner",
    "ModelConfig",
    "OutputConfig",
    "PipelineRunner",
    "PreprocessConfig",
    "Registry",
    "Reranker",
    "RetrievalConfig",
    "Retriever",
    "RuntimeConfig",
    "Source",
    "SourceConfig",
    "SourcesConfig",
    "TrainingConfig",
    "__version__",
    "canonical_json",
    "component_map",
    "dump_config",
    "file_sha256",
    "fingerprint",
    "load_config",
    "register",
    "register_builtin_components",
    "registry",
]
